language: rust
rust:
  - stable
  - beta
  - nightly

# See https://github.com/carllerche/travis-rust-matrix
env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
