[package]
name = "snmp"
version = "0.1.1"
authors = ["Hroi Sigurdsson <hroi@asdf.dk>"]
description = "SNMP client library"
license = "MIT/Apache-2.0"
repository = "https://github.com/hroi/rust-snmp"
documentation = "https://hroi.github.com/snmp/"
readme = "README.md"
keywords = ["networking", "snmp", "monitoring"]
exclude = ["src/private"]

[dependencies]

[features]
private-tests = []
